/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Admin;
import Model.Person;
import Model.Resident;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sakshi Sasalate
 */
public class AddPersonData extends javax.swing.JPanel {
    private JPanel lowerPanel;
    Admin admin;
    /**
     * Creates new form AddPersonData
     */
    public AddPersonData(JPanel lowerPanel, Admin admin) {
        initComponents();
        this.lowerPanel = lowerPanel;
        this.admin = admin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPersonPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        genderTF = new javax.swing.JTextField();
        ageTF = new javax.swing.JTextField();
        hgTF = new javax.swing.JTextField();
        bpTF = new javax.swing.JTextField();
        pastIllnessTF = new javax.swing.JTextField();
        communityTF = new javax.swing.JTextField();
        cityTF = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        saveDetailsButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        illnessTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        houseTF = new javax.swing.JTextField();
        isPatientCB = new javax.swing.JCheckBox();
        patientStatusTF = new javax.swing.JTextField();
        nameVal = new javax.swing.JLabel();
        genderVal = new javax.swing.JLabel();
        ageVal = new javax.swing.JLabel();
        pulseVal = new javax.swing.JLabel();
        bpVal = new javax.swing.JLabel();
        addPersonPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nameTF1 = new javax.swing.JTextField();
        genderTF1 = new javax.swing.JTextField();
        ageTF1 = new javax.swing.JTextField();
        hgTF1 = new javax.swing.JTextField();
        bpTF1 = new javax.swing.JTextField();
        pastIllnessTF1 = new javax.swing.JTextField();
        communityTF1 = new javax.swing.JTextField();
        cityTF1 = new javax.swing.JTextField();
        backButton1 = new javax.swing.JButton();
        saveDetailsButton1 = new javax.swing.JButton();
        clearButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        illnessTF1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        houseTF1 = new javax.swing.JTextField();
        isPatientCB1 = new javax.swing.JCheckBox();
        patientStatusTF1 = new javax.swing.JTextField();
        nameVal1 = new javax.swing.JLabel();
        genderVal1 = new javax.swing.JLabel();
        ageVal1 = new javax.swing.JLabel();
        pulseVal1 = new javax.swing.JLabel();
        bpVal1 = new javax.swing.JLabel();

        addPersonPanel.setBackground(new java.awt.Color(204, 204, 204));
        addPersonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ADD NEW PERSON C");
        addPersonPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("NAME :");
        addPersonPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 114, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setText("GENDER :");
        addPersonPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 168, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("AGE :");
        addPersonPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 221, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setText("PULSE :");
        addPersonPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 114, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setText("BP. :");
        addPersonPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 168, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setText("PAST ILLNESS :");
        addPersonPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 333, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setText("COMMUNITY :");
        addPersonPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 277, -1, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setText("CITY :");
        addPersonPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 333, -1, -1));

        nameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTFKeyReleased(evt);
            }
        });
        addPersonPanel.add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 113, 154, -1));

        genderTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                genderTFKeyReleased(evt);
            }
        });
        addPersonPanel.add(genderTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 167, 154, -1));

        ageTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ageTFKeyReleased(evt);
            }
        });
        addPersonPanel.add(ageTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 220, 154, -1));

        hgTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hgTFKeyReleased(evt);
            }
        });
        addPersonPanel.add(hgTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 112, 150, -1));

        bpTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bpTFKeyReleased(evt);
            }
        });
        addPersonPanel.add(bpTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 166, 150, -1));
        addPersonPanel.add(pastIllnessTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 332, 118, -1));
        addPersonPanel.add(communityTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 275, 140, -1));
        addPersonPanel.add(cityTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 332, 140, -1));

        backButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        addPersonPanel.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 107, 41));

        saveDetailsButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        saveDetailsButton.setText("SAVE ");
        saveDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDetailsButtonActionPerformed(evt);
            }
        });
        addPersonPanel.add(saveDetailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 90, 41));

        clearButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        addPersonPanel.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 110, 41));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setText("ILLNESS :");
        addPersonPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 277, -1, -1));
        addPersonPanel.add(illnessTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 276, 150, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel13.setText("HOUSE :");
        addPersonPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 221, -1, -1));

        houseTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                houseTFActionPerformed(evt);
            }
        });
        addPersonPanel.add(houseTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 220, 150, -1));

        isPatientCB.setBackground(new java.awt.Color(255, 255, 255));
        isPatientCB.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        isPatientCB.setText("IS PATIENT ?");
        isPatientCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isPatientCBActionPerformed(evt);
            }
        });
        addPersonPanel.add(isPatientCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, -1));

        patientStatusTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientStatusTFActionPerformed(evt);
            }
        });
        addPersonPanel.add(patientStatusTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 390, 130, -1));
        addPersonPanel.add(nameVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 140, 20));
        addPersonPanel.add(genderVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 150, 20));
        addPersonPanel.add(ageVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 160, 20));
        addPersonPanel.add(pulseVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 134, 150, 20));
        addPersonPanel.add(bpVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 140, 20));

        addPersonPanel1.setBackground(new java.awt.Color(204, 204, 204));
        addPersonPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("ADD NEW PERSON");
        addPersonPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel12.setText("NAME :");
        addPersonPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 114, -1, -1));

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel14.setText("GENDER :");
        addPersonPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 168, -1, -1));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel15.setText("AGE :");
        addPersonPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 221, -1, -1));

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel16.setText("PULSE :");
        addPersonPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 114, -1, -1));

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel17.setText("BP. :");
        addPersonPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 168, -1, -1));

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel18.setText("PAST ILLNESS :");
        addPersonPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 333, -1, -1));

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel19.setText("COMMUNITY :");
        addPersonPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 277, -1, -1));

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel20.setText("CITY :");
        addPersonPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 333, -1, -1));

        nameTF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTF1KeyReleased(evt);
            }
        });
        addPersonPanel1.add(nameTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 113, 154, -1));

        genderTF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                genderTF1KeyReleased(evt);
            }
        });
        addPersonPanel1.add(genderTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 167, 154, -1));

        ageTF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ageTF1KeyReleased(evt);
            }
        });
        addPersonPanel1.add(ageTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 220, 154, -1));

        hgTF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hgTF1KeyReleased(evt);
            }
        });
        addPersonPanel1.add(hgTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 112, 150, -1));

        bpTF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bpTF1KeyReleased(evt);
            }
        });
        addPersonPanel1.add(bpTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 166, 150, -1));
        addPersonPanel1.add(pastIllnessTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 332, 118, -1));
        addPersonPanel1.add(communityTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 275, 140, -1));
        addPersonPanel1.add(cityTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 332, 140, -1));

        backButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        backButton1.setText("BACK");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        addPersonPanel1.add(backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 107, 41));

        saveDetailsButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        saveDetailsButton1.setText("SAVE ");
        saveDetailsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDetailsButton1ActionPerformed(evt);
            }
        });
        addPersonPanel1.add(saveDetailsButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 90, 41));

        clearButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        clearButton1.setText("CLEAR");
        clearButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButton1ActionPerformed(evt);
            }
        });
        addPersonPanel1.add(clearButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 110, 41));

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel21.setText("ILLNESS :");
        addPersonPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 277, -1, -1));
        addPersonPanel1.add(illnessTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 276, 150, -1));

        jLabel22.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel22.setText("HOUSE :");
        addPersonPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 221, -1, -1));

        houseTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                houseTF1ActionPerformed(evt);
            }
        });
        addPersonPanel1.add(houseTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 220, 150, -1));

        isPatientCB1.setBackground(new java.awt.Color(255, 255, 255));
        isPatientCB1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        isPatientCB1.setText("IS PATIENT ?");
        isPatientCB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isPatientCB1ActionPerformed(evt);
            }
        });
        addPersonPanel1.add(isPatientCB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, -1));

        patientStatusTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientStatusTF1ActionPerformed(evt);
            }
        });
        addPersonPanel1.add(patientStatusTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 390, 130, -1));
        addPersonPanel1.add(nameVal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 140, 20));
        addPersonPanel1.add(genderVal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 150, 20));
        addPersonPanel1.add(ageVal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 160, 20));
        addPersonPanel1.add(pulseVal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 134, 150, 20));
        addPersonPanel1.add(bpVal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 140, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addPersonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
            .addComponent(addPersonPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addPersonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addPersonPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void houseTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_houseTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_houseTFActionPerformed

    private void isPatientCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isPatientCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isPatientCBActionPerformed

    private void saveDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDetailsButtonActionPerformed
        // TODO add your handling code here:
        String name;
        int age;
        String gender;
        String city;
        String community;
        String house;
        String illness;
        String pastIllness;
        double BP;
        double HB;
        boolean isPatient;

        try{
             name= nameTF.getText();
             gender = genderTF.getText();
             age = Integer.parseInt(ageTF.getText());
             city = cityTF.getText();
             community = communityTF.getText();
             house = houseTF.getText();
             illness = illnessTF.getText();
             pastIllness = pastIllnessTF.getText();

              if (isPatientCB.isSelected()) {
                   patientStatusTF.setText("YES");
                   isPatient = true;
              } else {
                   patientStatusTF.setText("NO");
                   isPatient = false;
                }
             BP = Double.parseDouble(bpTF.getText());
             HB = Double.parseDouble(hgTF.getText());
             
        }catch(Exception e){
             JOptionPane.showMessageDialog(this, "Please recheck info entered!", "Info", JOptionPane.INFORMATION_MESSAGE);
             return;
         }
//adding person to directory
        Resident residence = new Resident(house, community, city);
        Person person  = new Person(name, age, gender, illness, pastIllness, residence, isPatient, BP, HB);
        this.admin.addPerson(person);
        JOptionPane.showMessageDialog(this, "Person added successfully!", "Info", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_saveDetailsButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        CommunityPersonDirectory CommunityPersonDirectory = new CommunityPersonDirectory(lowerPanel, admin);
        lowerPanel.add("personWindow",CommunityPersonDirectory);
        CardLayout layout = (CardLayout)lowerPanel.getLayout();
        layout.next(lowerPanel);
    }//GEN-LAST:event_backButtonActionPerformed

    private void patientStatusTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientStatusTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientStatusTFActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        nameTF.setText("");
        genderTF.setText("");
        ageTF.setText("");
        illnessTF.setText("");
        pastIllnessTF.setText("");
        hgTF.setText("");
        bpTF.setText("");
        houseTF.setText("");
        communityTF.setText("");
        cityTF.setText("");
//        isPatientCB.isSelected(false);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void nameTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTFKeyReleased
        // TODO add your handling code here:
        String Name ="^[a-zA-Z\\s]{0,30}$";
        Pattern p = Pattern.compile(Name);
        Matcher match= p.matcher(nameTF.getText());
        if(!match.matches()){
            nameVal.setText("Invalid input!");
        }
        else {
            nameVal.setText("");
        }
    }//GEN-LAST:event_nameTFKeyReleased

    private void genderTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_genderTFKeyReleased
        // TODO add your handling code here:
        String Name ="^[a-zA-Z\\s]{0,30}$";
        Pattern p = Pattern.compile(Name);
        Matcher match= p.matcher(genderTF.getText());
        if(!match.matches()){
            genderVal.setText("Invalid input!");
        }
        else {
            genderVal.setText("");
        }
    }//GEN-LAST:event_genderTFKeyReleased

    private void ageTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTFKeyReleased
        // TODO add your handling code here:
        String age ="^[0-9]{0,10}$";
        Pattern p = Pattern.compile(age);
        Matcher match= p.matcher(ageTF.getText());
        if(!match.matches()){
            ageVal.setText("Invalid! Only numeric input");
        }
        else {
                ageVal.setText("");
    }
    }//GEN-LAST:event_ageTFKeyReleased

    private void hgTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hgTFKeyReleased
        // TODO add your handling code here:
        String str ="^[0-9]{0,10}$";
        Pattern p = Pattern.compile(str);
        Matcher match= p.matcher(hgTF.getText());
        if(!match.matches()){
            pulseVal.setText("Invalid! Only numeric input");
        }
        else {
                pulseVal.setText("");
    }
    }//GEN-LAST:event_hgTFKeyReleased

    private void bpTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bpTFKeyReleased
        // TODO add your handling code here:
        String str ="^[0-9]{0,10}$";
        Pattern p = Pattern.compile(str);
        Matcher match= p.matcher(bpTF.getText());
        if(!match.matches()){
            bpVal.setText("Invalid! Only numeric input");
        }
        else {
                bpVal.setText("");
        }
    }//GEN-LAST:event_bpTFKeyReleased

    private void nameTF1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTF1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTF1KeyReleased

    private void genderTF1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_genderTF1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_genderTF1KeyReleased

    private void ageTF1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTF1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTF1KeyReleased

    private void hgTF1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hgTF1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_hgTF1KeyReleased

    private void bpTF1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bpTF1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_bpTF1KeyReleased

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButton1ActionPerformed

    private void saveDetailsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDetailsButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveDetailsButton1ActionPerformed

    private void clearButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearButton1ActionPerformed

    private void houseTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_houseTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_houseTF1ActionPerformed

    private void isPatientCB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isPatientCB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isPatientCB1ActionPerformed

    private void patientStatusTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientStatusTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientStatusTF1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPersonPanel;
    private javax.swing.JPanel addPersonPanel1;
    private javax.swing.JTextField ageTF;
    private javax.swing.JTextField ageTF1;
    private javax.swing.JLabel ageVal;
    private javax.swing.JLabel ageVal1;
    private javax.swing.JButton backButton;
    private javax.swing.JButton backButton1;
    private javax.swing.JTextField bpTF;
    private javax.swing.JTextField bpTF1;
    private javax.swing.JLabel bpVal;
    private javax.swing.JLabel bpVal1;
    private javax.swing.JTextField cityTF;
    private javax.swing.JTextField cityTF1;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton clearButton1;
    private javax.swing.JTextField communityTF;
    private javax.swing.JTextField communityTF1;
    private javax.swing.JTextField genderTF;
    private javax.swing.JTextField genderTF1;
    private javax.swing.JLabel genderVal;
    private javax.swing.JLabel genderVal1;
    private javax.swing.JTextField hgTF;
    private javax.swing.JTextField hgTF1;
    private javax.swing.JTextField houseTF;
    private javax.swing.JTextField houseTF1;
    private javax.swing.JTextField illnessTF;
    private javax.swing.JTextField illnessTF1;
    private javax.swing.JCheckBox isPatientCB;
    private javax.swing.JCheckBox isPatientCB1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField nameTF1;
    private javax.swing.JLabel nameVal;
    private javax.swing.JLabel nameVal1;
    private javax.swing.JTextField pastIllnessTF;
    private javax.swing.JTextField pastIllnessTF1;
    private javax.swing.JTextField patientStatusTF;
    private javax.swing.JTextField patientStatusTF1;
    private javax.swing.JLabel pulseVal;
    private javax.swing.JLabel pulseVal1;
    private javax.swing.JButton saveDetailsButton;
    private javax.swing.JButton saveDetailsButton1;
    // End of variables declaration//GEN-END:variables
}
